name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile
        run: make

      # Runs a set of commands using the runners shell
      - name: Run
        run: ./hello

      # Runs a set of commands using the runners shell
      - name: Clean
        run: make clean

